version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - zen_network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_postgres_user
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: your_postgres_db
    ports:
      - "5432:5432"
    networks:
      - zen_network

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
    networks:
      - zen_network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - zen_network

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3001:3000"
    networks:
      - zen_network

  nginx:
    image: nginx:latest
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - zen_network

  zenbreeder:
    depends_on:
      - redis
      - postgres
    build:
      context: ./ZenBreeder
    ports:
      - "8080:8080"
    volumes:
      - ./ZenBreeder:/app
    networks:
      - zen_network

  zenlexicon:
    depends_on:
      - redis
      - postgres
    build:
      context: ./ZenLexicon
    ports:
      - "8081:8081"
    volumes:
      - ./ZenLexicon:/app
    networks:
      - zen_network

  zentank:
    depends_on:
      - redis
      - postgres
    build:
      context: ./ZenTank
    ports:
      - "8082:8082"
    volumes:
      - ./ZenTank:/app
    networks:
      - zen_network

  ui:
    depends_on:
      - zenbreeder
      - zenlexicon
      - zentank
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - zen_network

networks:
  zen_network:
    driver: bridge