name: ZenTank Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: 'ZenTank' # Checkout only the ZenTank directory

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.1

      - name: Build
        run: go build

      - name: Run tests
        run: go test ./...
